// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7sBW0HLWFxTTqGN_scTZLQI5xr6Sme7o',
    appId: '1:508573040432:web:3eb76ffe91dacd4a1fd2f5',
    messagingSenderId: '508573040432',
    projectId: 'draftv2',
    authDomain: 'draftv2.firebaseapp.com',
    storageBucket: 'draftv2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDm9n6BhTR6a7zYm5MqHmPtXIgZ_esxk98',
    appId: '1:508573040432:android:e494c882ffaeee8e1fd2f5',
    messagingSenderId: '508573040432',
    projectId: 'draftv2',
    storageBucket: 'draftv2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvP3UMQ8oH2vBqN_DbaBQsQI9nggjXs_g',
    appId: '1:508573040432:ios:13d4579a47c65f6a1fd2f5',
    messagingSenderId: '508573040432',
    projectId: 'draftv2',
    storageBucket: 'draftv2.appspot.com',
    iosBundleId: 'com.google.firebase.presents.crowdcuts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvP3UMQ8oH2vBqN_DbaBQsQI9nggjXs_g',
    appId: '1:508573040432:ios:bce9a93f5f1ddbe31fd2f5',
    messagingSenderId: '508573040432',
    projectId: 'draftv2',
    storageBucket: 'draftv2.appspot.com',
    iosBundleId: 'com.google.firebase.presents.crowdcuts.RunnerTests',
  );
}
